export const commonRecipe = [
  {
    id: 1,
    name: 'Dal Bhat',
    time: 'Lunch/Dinner',
    calories: 500,
    dietType: 'Vegetarian',
    description:
      'Steamed rice served with lentil soup and vegetable curries, a staple Nepali meal.',
  },
  {
    id: 2,
    name: 'Momo',
    time: 'Any',
    calories: 300,
    dietType: 'Vegetarian/Non-vegetarian',
    description:
      'Dumplings filled with vegetables or meat, served with spicy tomato chutney.',
  },
  {
    id: 3,
    name: 'Pani Puri',
    time: 'Snack',
    calories: 150,
    dietType: 'Vegetarian',
    description:
      'Hollow crispy balls filled with spiced potatoes, chickpeas, and tangy tamarind water.',
  },
  {
    id: 4,
    name: 'Sel Roti',
    time: 'Breakfast/Snack',
    calories: 250,
    dietType: 'Vegetarian',
    description:
      'Traditional homemade ring-shaped rice bread/doughnut, often served during festivals.',
  },
  {
    id: 5,
    name: 'Chatamari',
    time: 'Any',
    calories: 200,
    dietType: 'Vegetarian/Non-vegetarian',
    description:
      'Newari rice crepe topped with minced meat, eggs, or vegetables.',
  },
  {
    id: 6,
    name: 'Yomari',
    time: 'Snack',
    calories: 180,
    dietType: 'Vegetarian',
    description:
      'Steamed dumpling made of rice flour with sweet fillings like chaku (molasses) or khuwa.',
  },
  {
    id: 7,
    name: 'Gundruk',
    time: 'Side',
    calories: 50,
    dietType: 'Vegetarian',
    description:
      'Fermented leafy green vegetable, typically served as soup or pickle.',
  },
  {
    id: 8,
    name: 'Sukuti',
    time: 'Side/Snack',
    calories: 200,
    dietType: 'Non-vegetarian',
    description: "Dried meat (usually buffalo or goat) that's spicy and chewy.",
  },
  {
    id: 9,
    name: 'Bara',
    time: 'Any',
    calories: 250,
    dietType: 'Vegetarian/Non-vegetarian',
    description:
      'Savory lentil pancake, a Newari specialty often served with eggs or meat toppings.',
  },
  {
    id: 10,
    name: 'Aloo Tama',
    time: 'Lunch/Dinner',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Unique sour soup made with bamboo shoots and potatoes.',
  },
  {
    id: 11,
    name: 'Kwati',
    time: 'Lunch/Dinner',
    calories: 350,
    dietType: 'Vegetarian',
    description:
      'Mixed bean soup traditionally eaten during Gunla (Buddhist holy month).',
  },
  {
    id: 12,
    name: 'Thukpa',
    time: 'Lunch/Dinner',
    calories: 400,
    dietType: 'Vegetarian/Non-vegetarian',
    description:
      'Noodle soup with vegetables and optional meat, influenced by Tibetan cuisine.',
  },
  {
    id: 13,
    name: 'Choila',
    time: 'Side/Snack',
    calories: 250,
    dietType: 'Non-vegetarian',
    description:
      'Spicy grilled buffalo meat, a Newari delicacy often served with beaten rice.',
  },
  {
    id: 14,
    name: 'Juju Dhau',
    time: 'Dessert',
    calories: 150,
    dietType: 'Vegetarian',
    description:
      'King of yogurts, a sweet and creamy yogurt specialty from Bhaktapur.',
  },
  {
    id: 15,
    name: 'Samay Baji',
    time: 'Lunch/Dinner',
    calories: 450,
    dietType: 'Vegetarian/Non-vegetarian',
    description:
      'Traditional Newari platter with beaten rice, smoked fish, boiled egg, black soybeans, and more.',
  },
  {
    id: 16,
    name: 'Wo',
    time: 'Any',
    calories: 200,
    dietType: 'Vegetarian/Non-vegetarian',
    description:
      'Lentil pancake, another Newari specialty similar to Bara but thinner.',
  },
  {
    id: 17,
    name: 'Lakhamari',
    time: 'Dessert/Snack',
    calories: 180,
    dietType: 'Vegetarian',
    description:
      'Sweet, deep-fried Newari biscuit traditionally given in weddings.',
  },
  {
    id: 18,
    name: 'Sekuwa',
    time: 'Snack',
    calories: 300,
    dietType: 'Non-vegetarian',
    description: 'Grilled meat (chicken, pork, or mutton) marinated in spices.',
  },
  {
    id: 19,
    name: 'Yak Cheese',
    time: 'Snack',
    calories: 200,
    dietType: 'Vegetarian',
    description:
      'Hard cheese made from yak milk, popular in Himalayan regions.',
  },
  {
    id: 20,
    name: 'Bhatmas Sadeko',
    time: 'Side/Snack',
    calories: 150,
    dietType: 'Vegetarian',
    description: 'Spiced soybean salad with onions, tomatoes, and chili.',
  },
  {
    id: 21,
    name: 'Aalu Achaar',
    time: 'Side',
    calories: 100,
    dietType: 'Vegetarian',
    description: 'Spicy potato pickle served as a side dish.',
  },
  {
    id: 22,
    name: 'Masu Bhat',
    time: 'Lunch/Dinner',
    calories: 550,
    dietType: 'Non-vegetarian',
    description:
      'Rice served with meat curry (usually chicken, mutton, or buffalo).',
  },
  {
    id: 23,
    name: 'Pulao',
    time: 'Lunch/Dinner',
    calories: 450,
    dietType: 'Vegetarian/Non-vegetarian',
    description:
      'Fragrant rice cooked with spices, vegetables and sometimes meat.',
  },
  {
    id: 24,
    name: 'Chana Tarkari',
    time: 'Lunch/Dinner',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Chickpea curry served with rice or roti.',
  },
  {
    id: 25,
    name: 'Saag',
    time: 'Side',
    calories: 100,
    dietType: 'Vegetarian',
    description:
      'Cooked leafy greens (spinach, mustard, or other local varieties).',
  },
  {
    id: 26,
    name: 'Tama',
    time: 'Side',
    calories: 80,
    dietType: 'Vegetarian',
    description: 'Fermented bamboo shoots used in curries and soups.',
  },
  {
    id: 27,
    name: 'Kachila',
    time: 'Side/Snack',
    calories: 180,
    dietType: 'Non-vegetarian',
    description:
      'Raw minced buffalo meat mixed with spices, a Newari delicacy.',
  },
  {
    id: 28,
    name: 'Sanya Khuna',
    time: 'Side/Snack',
    calories: 200,
    dietType: 'Non-vegetarian',
    description: 'Jellied fish soup, a Newari specialty.',
  },
  {
    id: 29,
    name: 'Baji',
    time: 'Any',
    calories: 200,
    dietType: 'Vegetarian',
    description:
      'Beaten rice (chiura), commonly eaten with yogurt, curry or as snacks.',
  },
  {
    id: 30,
    name: 'Chhurpi',
    time: 'Snack',
    calories: 150,
    dietType: 'Vegetarian',
    description: 'Hard cheese made from yak or cow milk, eaten as snack.',
  },
  {
    id: 31,
    name: 'Piro Aalu',
    time: 'Side/Snack',
    calories: 150,
    dietType: 'Vegetarian',
    description: 'Spicy boiled potatoes seasoned with mustard oil and spices.',
  },
  {
    id: 32,
    name: 'Gorkhali Lamb',
    time: 'Lunch/Dinner',
    calories: 400,
    dietType: 'Non-vegetarian',
    description: 'Slow-cooked lamb in rich gravy with Nepali spices.',
  },
  {
    id: 33,
    name: 'Dhido',
    time: 'Lunch/Dinner',
    calories: 300,
    dietType: 'Vegetarian',
    description:
      'Traditional thick porridge made from buckwheat or millet flour.',
  },
  {
    id: 34,
    name: 'Sinki',
    time: 'Side',
    calories: 60,
    dietType: 'Vegetarian',
    description:
      'Fermented radish taproot, similar to gundruk but made from radish.',
  },
  {
    id: 35,
    name: 'Kinema',
    time: 'Side',
    calories: 120,
    dietType: 'Vegetarian',
    description:
      'Fermented soybean product similar to natto, eaten in eastern Nepal.',
  },
  {
    id: 36,
    name: 'Masaura',
    time: 'Side',
    calories: 150,
    dietType: 'Vegetarian',
    description: 'Dried balls of fermented black lentils, used in curries.',
  },
  {
    id: 37,
    name: 'Bhatti Ko Masu',
    time: 'Lunch/Dinner',
    calories: 450,
    dietType: 'Non-vegetarian',
    description: 'Spicy meat curry cooked in traditional Nepali style.',
  },
  {
    id: 38,
    name: 'Kodo Ko Roti',
    time: 'Breakfast/Lunch',
    calories: 200,
    dietType: 'Vegetarian',
    description:
      'Flatbread made from finger millet flour, common in hilly regions.',
  },
  {
    id: 39,
    name: 'Makai Ko Roti',
    time: 'Breakfast/Lunch',
    calories: 220,
    dietType: 'Vegetarian',
    description: 'Corn flour flatbread, popular in Terai region.',
  },
  {
    id: 40,
    name: 'Chataamari',
    time: 'Any',
    calories: 180,
    dietType: 'Vegetarian/Non-vegetarian',
    description: "Newari rice flour crepe, sometimes called 'Nepali pizza'.",
  },
  {
    id: 41,
    name: 'Yomari Punhi',
    time: 'Snack',
    calories: 200,
    dietType: 'Vegetarian',
    description:
      'Sweet version of yomari filled with molasses and sesame seeds.',
  },
  {
    id: 42,
    name: 'Masyaura Ko Tarkari',
    time: 'Lunch/Dinner',
    calories: 180,
    dietType: 'Vegetarian',
    description: 'Curry made with fermented lentil balls and vegetables.',
  },
  {
    id: 43,
    name: 'Ghyu Chaku',
    time: 'Dessert',
    calories: 250,
    dietType: 'Vegetarian',
    description:
      'Clarified butter (ghee) with hardened molasses, a winter delicacy.',
  },
  {
    id: 44,
    name: 'Pustakari',
    time: 'Dessert',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Sweet made from milk solids and sugar, shaped like books.',
  },
  {
    id: 45,
    name: 'Anarsa',
    time: 'Dessert/Snack',
    calories: 180,
    dietType: 'Vegetarian',
    description:
      'Sweet rice flour cookies with sesame seeds, popular in Terai.',
  },
  {
    id: 46,
    name: 'Thekuwa',
    time: 'Snack',
    calories: 150,
    dietType: 'Vegetarian',
    description:
      'Deep-fried sweet wheat flour cookies, common during festivals.',
  },
  {
    id: 47,
    name: 'Simal Tarul',
    time: 'Snack',
    calories: 100,
    dietType: 'Vegetarian',
    description: 'Boiled taro root, often eaten with salt and chili.',
  },
  {
    id: 48,
    name: 'Ghonghi',
    time: 'Side',
    calories: 120,
    dietType: 'Non-vegetarian',
    description: 'Freshwater snails cooked in spicy gravy, popular in Terai.',
  },
  {
    id: 49,
    name: 'Bodi Ko Achar',
    time: 'Side',
    calories: 100,
    dietType: 'Vegetarian',
    description: 'Spicy black-eyed pea pickle.',
  },
  {
    id: 50,
    name: 'Sukul Ko Masu',
    time: 'Lunch/Dinner',
    calories: 350,
    dietType: 'Non-vegetarian',
    description: 'Dried fish curry, popular in hilly regions.',
  },
  {
    id: 51,
    name: 'Phapar Ko Roti',
    time: 'Breakfast/Lunch',
    calories: 180,
    dietType: 'Vegetarian',
    description: 'Buckwheat flatbread, staple in mountainous regions.',
  },
  {
    id: 52,
    name: 'Tingmo',
    time: 'Breakfast/Snack',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Steamed Tibetan bread often served with curry.',
  },
  {
    id: 53,
    name: 'Shyaphale',
    time: 'Snack',
    calories: 250,
    dietType: 'Non-vegetarian',
    description: 'Deep-fried meat-stuffed bread, Tibetan influence.',
  },
  {
    id: 54,
    name: 'Thenthuk',
    time: 'Lunch/Dinner',
    calories: 350,
    dietType: 'Vegetarian/Non-vegetarian',
    description: 'Hand-pulled noodle soup with vegetables and optional meat.',
  },
  {
    id: 55,
    name: 'Rikikul',
    time: 'Snack',
    calories: 150,
    dietType: 'Vegetarian',
    description: 'Thin buckwheat pancakes from Mustang region.',
  },
  {
    id: 56,
    name: 'Chhoyala',
    time: 'Side/Snack',
    calories: 220,
    dietType: 'Non-vegetarian',
    description: 'Marinated grilled meat cubes, Newari style.',
  },
  {
    id: 57,
    name: 'Kachila',
    time: 'Side/Snack',
    calories: 180,
    dietType: 'Non-vegetarian',
    description: 'Raw minced meat salad with spices.',
  },
  {
    id: 58,
    name: 'Laping',
    time: 'Snack',
    calories: 120,
    dietType: 'Vegetarian',
    description: 'Cold mung bean starch noodle with spicy sauce.',
  },
  {
    id: 59,
    name: 'Yartsa Gunbu',
    time: 'Special',
    calories: 100,
    dietType: 'Non-vegetarian',
    description: 'Caterpillar fungus, expensive medicinal ingredient.',
  },
  {
    id: 60,
    name: 'Khir',
    time: 'Dessert',
    calories: 300,
    dietType: 'Vegetarian',
    description: 'Rice pudding made with milk and sugar.',
  },
  {
    id: 61,
    name: 'Gajar Ko Halwa',
    time: 'Dessert',
    calories: 350,
    dietType: 'Vegetarian',
    description: 'Carrot pudding made with milk and ghee.',
  },
  {
    id: 62,
    name: 'Badam Ko Halwa',
    time: 'Dessert',
    calories: 400,
    dietType: 'Vegetarian',
    description: 'Almond pudding, rich festival sweet.',
  },
  {
    id: 63,
    name: 'Malpuwa',
    time: 'Dessert/Snack',
    calories: 250,
    dietType: 'Vegetarian',
    description: 'Sweet fried pancakes soaked in sugar syrup.',
  },
  {
    id: 64,
    name: 'Haluwa',
    time: 'Dessert',
    calories: 300,
    dietType: 'Vegetarian',
    description: 'Semolina pudding with nuts and ghee.',
  },
  {
    id: 65,
    name: 'Mohan Bhog',
    time: 'Dessert',
    calories: 280,
    dietType: 'Vegetarian',
    description: 'Sweetened rice flour dessert with saffron.',
  },
  {
    id: 66,
    name: 'Sarbat',
    time: 'Drink',
    calories: 150,
    dietType: 'Vegetarian',
    description: 'Sweet rose-flavored milk drink.',
  },
  {
    id: 67,
    name: 'Chiya',
    time: 'Drink',
    calories: 50,
    dietType: 'Vegetarian',
    description: 'Nepali milk tea with spices.',
  },
  {
    id: 68,
    name: 'Tongba',
    time: 'Drink',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Fermented millet alcoholic beverage.',
  },
  {
    id: 69,
    name: 'Raksi',
    time: 'Drink',
    calories: 250,
    dietType: 'Vegetarian',
    description: 'Traditional Nepali distilled alcohol.',
  },
  {
    id: 70,
    name: 'Chyang',
    time: 'Drink',
    calories: 180,
    dietType: 'Vegetarian',
    description: 'Rice beer popular in Newari culture.',
  },
  {
    id: 71,
    name: 'Lassi',
    time: 'Drink',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Yogurt-based drink, sweet or salty.',
  },
  {
    id: 72,
    name: 'Nimbu Pani',
    time: 'Drink',
    calories: 80,
    dietType: 'Vegetarian',
    description: 'Fresh lemonade with salt and spices.',
  },
  {
    id: 73,
    name: 'Aalu Ko Achar',
    time: 'Side',
    calories: 120,
    dietType: 'Vegetarian',
    description: 'Spicy potato pickle with mustard oil.',
  },
  {
    id: 74,
    name: 'Gundruk Ko Achar',
    time: 'Side',
    calories: 60,
    dietType: 'Vegetarian',
    description: 'Pickle made from fermented greens.',
  },
  {
    id: 75,
    name: 'Mula Ko Achar',
    time: 'Side',
    calories: 70,
    dietType: 'Vegetarian',
    description: 'Spicy radish pickle.',
  },
  {
    id: 76,
    name: 'Dalle Khursani Achar',
    time: 'Side',
    calories: 50,
    dietType: 'Vegetarian',
    description: 'Fiery hot chili pickle.',
  },
  {
    id: 77,
    name: 'Ledo',
    time: 'Lunch/Dinner',
    calories: 400,
    dietType: 'Vegetarian/Non-vegetarian',
    description: 'Thick stew from eastern Nepal.',
  },
  {
    id: 78,
    name: 'Kachila',
    time: 'Side/Snack',
    calories: 180,
    dietType: 'Non-vegetarian',
    description: 'Raw minced meat with spices.',
  },
  {
    id: 79,
    name: 'Simal Ko Tusa',
    time: 'Side',
    calories: 90,
    dietType: 'Vegetarian',
    description: 'Bamboo shoot curry.',
  },
  {
    id: 80,
    name: 'Karkalo',
    time: 'Side',
    calories: 80,
    dietType: 'Vegetarian',
    description: 'Taro leaves cooked with spices.',
  },
  {
    id: 81,
    name: 'Bhatte Ko Chura',
    time: 'Breakfast/Snack',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Beaten rice from fresh rice.',
  },
  {
    id: 82,
    name: 'Makai Ko Dhido',
    time: 'Lunch/Dinner',
    calories: 300,
    dietType: 'Vegetarian',
    description: 'Corn flour porridge.',
  },
  {
    id: 83,
    name: 'Kodo Ko Dhido',
    time: 'Lunch/Dinner',
    calories: 280,
    dietType: 'Vegetarian',
    description: 'Finger millet porridge.',
  },
  {
    id: 84,
    name: 'Phapar Ko Dhido',
    time: 'Lunch/Dinner',
    calories: 250,
    dietType: 'Vegetarian',
    description: 'Buckwheat porridge.',
  },
  {
    id: 85,
    name: 'Gahute Ko Roti',
    time: 'Breakfast/Lunch',
    calories: 180,
    dietType: 'Vegetarian',
    description: 'Wheat flatbread from mountain regions.',
  },
  {
    id: 86,
    name: 'Chamre',
    time: 'Side',
    calories: 120,
    dietType: 'Non-vegetarian',
    description: 'Fried fish from Himalayan rivers.',
  },
  {
    id: 87,
    name: 'Pindalu',
    time: 'Side',
    calories: 100,
    dietType: 'Vegetarian',
    description: 'Taro root curry.',
  },
  {
    id: 88,
    name: 'Maseura',
    time: 'Side',
    calories: 150,
    dietType: 'Vegetarian',
    description: 'Sun-dried lentil balls used in curries.',
  },
  {
    id: 89,
    name: 'Golbheda Ko Achar',
    time: 'Side',
    calories: 90,
    dietType: 'Vegetarian',
    description: 'Tomato pickle with spices.',
  },
  {
    id: 90,
    name: 'Lapsi',
    time: 'Dessert',
    calories: 220,
    dietType: 'Vegetarian',
    description: 'Tart fruit made into sweet candy.',
  },
  {
    id: 91,
    name: 'Aiselu',
    time: 'Snack',
    calories: 50,
    dietType: 'Vegetarian',
    description: 'Wild Himalayan raspberries.',
  },
  {
    id: 92,
    name: 'Kafal',
    time: 'Snack',
    calories: 60,
    dietType: 'Vegetarian',
    description: 'Red wild berries from hills.',
  },
  {
    id: 93,
    name: 'Chutro',
    time: 'Snack',
    calories: 70,
    dietType: 'Vegetarian',
    description: 'Himalayan wild berries.',
  },
  {
    id: 94,
    name: 'Aduwa',
    time: 'Snack',
    calories: 80,
    dietType: 'Vegetarian',
    description: 'Ginger candy.',
  },
  {
    id: 95,
    name: 'Simal Tarul',
    time: 'Snack',
    calories: 100,
    dietType: 'Vegetarian',
    description: 'Boiled taro root.',
  },
  {
    id: 96,
    name: 'Ghyu',
    time: 'Ingredient',
    calories: 120,
    dietType: 'Vegetarian',
    description: 'Clarified butter used in cooking.',
  },
  {
    id: 97,
    name: 'Chhurpi Soup',
    time: 'Lunch/Dinner',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Soup made from hard cheese.',
  },
  {
    id: 98,
    name: 'Pustakari',
    time: 'Dessert',
    calories: 180,
    dietType: 'Vegetarian',
    description: 'Milk-based sweet shaped like books.',
  },
  {
    id: 99,
    name: 'Anarsa',
    time: 'Dessert',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Rice flour cookies with sesame.',
  },
  {
    id: 100,
    name: 'Bara Musya',
    time: 'Snack',
    calories: 250,
    dietType: 'Non-vegetarian',
    description: 'Lentil pancake with minced meat.',
  },
  {
    id: 101,
    name: 'Jeri',
    time: 'Dessert/Snack',
    calories: 280,
    dietType: 'Vegetarian',
    description:
      'Deep-fried swirls of dough soaked in sugar syrup, similar to jalebi.',
  },
  {
    id: 102,
    name: 'Peda',
    time: 'Dessert',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Sweet milk-based fudge, often flavored with cardamom.',
  },
  {
    id: 103,
    name: 'Gundruk Ko Jhol',
    time: 'Side/Soup',
    calories: 80,
    dietType: 'Vegetarian',
    description: 'Soup made from fermented leafy greens, tangy and nutritious.',
  },
  {
    id: 104,
    name: 'Chukauni',
    time: 'Side',
    calories: 150,
    dietType: 'Vegetarian',
    description:
      'Yogurt-based potato salad with spices, popular in western Nepal.',
  },
  {
    id: 105,
    name: 'Kwati Soup',
    time: 'Lunch/Dinner',
    calories: 300,
    dietType: 'Vegetarian',
    description: 'Mixed bean soup, traditionally eaten during Janai Purnima.',
  },
  {
    id: 106,
    name: 'Bhatti Ko Chiya',
    time: 'Drink',
    calories: 70,
    dietType: 'Vegetarian',
    description: 'Strong milk tea served in roadside teashops.',
  },
  {
    id: 107,
    name: 'Simal Ko Chhop',
    time: 'Side',
    calories: 90,
    dietType: 'Vegetarian',
    description: 'Bamboo shoot pickle, tangy and spicy.',
  },
  {
    id: 108,
    name: 'Masyaura Soup',
    time: 'Lunch/Dinner',
    calories: 180,
    dietType: 'Vegetarian',
    description: 'Soup made from dried lentil balls and greens.',
  },
  {
    id: 109,
    name: 'Kalo Dal',
    time: 'Lunch/Dinner',
    calories: 250,
    dietType: 'Vegetarian',
    description: 'Black lentil curry, rich and flavorful.',
  },
  {
    id: 110,
    name: 'Bodi Ko Tarkari',
    time: 'Lunch/Dinner',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Black-eyed pea curry, common in Terai.',
  },
  {
    id: 111,
    name: 'Kheer',
    time: 'Dessert',
    calories: 320,
    dietType: 'Vegetarian',
    description: 'Creamy rice pudding with nuts and cardamom.',
  },
  {
    id: 112,
    name: 'Masaura Ko Tarkari',
    time: 'Lunch/Dinner',
    calories: 220,
    dietType: 'Vegetarian',
    description: 'Curry made with sun-dried lentil balls.',
  },
  {
    id: 113,
    name: 'Golbheda Ko Achar',
    time: 'Side',
    calories: 100,
    dietType: 'Vegetarian',
    description: 'Spicy tomato pickle with mustard oil.',
  },
  {
    id: 114,
    name: 'Kodo Ko Jaanr',
    time: 'Drink',
    calories: 180,
    dietType: 'Vegetarian',
    description: 'Fermented millet beer from eastern Nepal.',
  },
  {
    id: 115,
    name: 'Bhatmas Ko Achar',
    time: 'Side',
    calories: 120,
    dietType: 'Vegetarian',
    description: 'Spicy soybean pickle.',
  },
  {
    id: 116,
    name: 'Ghyu Chaku',
    time: 'Dessert',
    calories: 250,
    dietType: 'Vegetarian',
    description: 'Hardened molasses served with ghee, a winter delicacy.',
  },
  {
    id: 117,
    name: 'Pustakari',
    time: 'Dessert',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Milk-based sweet shaped like small books.',
  },
  {
    id: 118,
    name: 'Simal Ko Tusa',
    time: 'Side',
    calories: 90,
    dietType: 'Vegetarian',
    description: 'Bamboo shoot curry, slightly sour.',
  },
  {
    id: 119,
    name: 'Masyaura Ko Tarkari',
    time: 'Lunch/Dinner',
    calories: 220,
    dietType: 'Vegetarian',
    description: 'Curry made with dried lentil balls.',
  },
  {
    id: 120,
    name: 'Kachila',
    time: 'Side/Snack',
    calories: 180,
    dietType: 'Non-vegetarian',
    description: 'Raw minced meat salad with spices.',
  },
  {
    id: 121,
    name: 'Chhurpi Ko Jhol',
    time: 'Lunch/Dinner',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Soup made from hard cheese, common in Sherpa cuisine.',
  },
  {
    id: 122,
    name: 'Piro Aalu',
    time: 'Side/Snack',
    calories: 150,
    dietType: 'Vegetarian',
    description: 'Spicy boiled potatoes with mustard oil.',
  },
  {
    id: 123,
    name: 'Lal Puri',
    time: 'Breakfast/Snack',
    calories: 180,
    dietType: 'Vegetarian',
    description: 'Deep-fried puffed bread, similar to poori.',
  },
  {
    id: 124,
    name: 'Bhatmas Sadeko',
    time: 'Side/Snack',
    calories: 150,
    dietType: 'Vegetarian',
    description: 'Spiced soybean salad with onions and chili.',
  },
  {
    id: 125,
    name: 'Gundruk Sadeko',
    time: 'Side',
    calories: 70,
    dietType: 'Vegetarian',
    description: 'Fermented greens mixed with spices.',
  },
  {
    id: 126,
    name: 'Sukuti Sadeko',
    time: 'Side/Snack',
    calories: 200,
    dietType: 'Non-vegetarian',
    description: 'Dried meat mixed with onions and spices.',
  },
  {
    id: 127,
    name: 'Mula Ko Saag',
    time: 'Side',
    calories: 80,
    dietType: 'Vegetarian',
    description: 'Cooked radish greens, slightly bitter.',
  },
  {
    id: 128,
    name: 'Karkalo Ko Saag',
    time: 'Side',
    calories: 90,
    dietType: 'Vegetarian',
    description: 'Taro leaves cooked with spices.',
  },
  {
    id: 129,
    name: 'Rayo Ko Saag',
    time: 'Side',
    calories: 85,
    dietType: 'Vegetarian',
    description: 'Mustard greens, slightly pungent.',
  },
  {
    id: 130,
    name: 'Bhatte Ko Roti',
    time: 'Breakfast/Lunch',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Flatbread made from fresh rice flour.',
  },
  {
    id: 131,
    name: 'Gundruk Ko Achar',
    time: 'Side',
    calories: 60,
    dietType: 'Vegetarian',
    description: 'Pickle made from fermented greens.',
  },
  {
    id: 132,
    name: 'Masyaura Ko Achar',
    time: 'Side',
    calories: 100,
    dietType: 'Vegetarian',
    description: 'Pickle made from dried lentil balls.',
  },
  {
    id: 133,
    name: 'Sukuti Ko Jhol',
    time: 'Lunch/Dinner',
    calories: 220,
    dietType: 'Non-vegetarian',
    description: 'Soup made from dried meat.',
  },
  {
    id: 134,
    name: 'Chhurpi Ko Achar',
    time: 'Side',
    calories: 120,
    dietType: 'Vegetarian',
    description: 'Pickle made from hard cheese.',
  },
  {
    id: 135,
    name: 'Ghyu Bhat',
    time: 'Lunch/Dinner',
    calories: 450,
    dietType: 'Vegetarian',
    description: 'Rice mixed with clarified butter (ghee).',
  },
  {
    id: 136,
    name: 'Chaku Bhat',
    time: 'Breakfast',
    calories: 350,
    dietType: 'Vegetarian',
    description: 'Rice mixed with hardened molasses.',
  },
  {
    id: 137,
    name: 'Til Ko Laddu',
    time: 'Dessert',
    calories: 250,
    dietType: 'Vegetarian',
    description: 'Sesame seed balls, eaten in winter.',
  },
  {
    id: 138,
    name: 'Makai Ko Roti',
    time: 'Breakfast/Lunch',
    calories: 220,
    dietType: 'Vegetarian',
    description: 'Corn flour flatbread, popular in Terai.',
  },
  {
    id: 139,
    name: 'Kodo Ko Roti',
    time: 'Breakfast/Lunch',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Finger millet flatbread, common in hills.',
  },
  {
    id: 140,
    name: 'Phapar Ko Roti',
    time: 'Breakfast/Lunch',
    calories: 180,
    dietType: 'Vegetarian',
    description: 'Buckwheat flatbread, eaten in mountainous regions.',
  },
  {
    id: 141,
    name: 'Gundruk Ko Thekuwa',
    time: 'Snack',
    calories: 150,
    dietType: 'Vegetarian',
    description: 'Deep-fried snack made with fermented greens.',
  },
  {
    id: 142,
    name: 'Masyaura Ko Thekuwa',
    time: 'Snack',
    calories: 160,
    dietType: 'Vegetarian',
    description: 'Deep-fried snack made with dried lentil balls.',
  },
  {
    id: 143,
    name: 'Bodi Ko Thekuwa',
    time: 'Snack',
    calories: 170,
    dietType: 'Vegetarian',
    description: 'Deep-fried snack made with black-eyed peas.',
  },
  {
    id: 144,
    name: 'Chana Ko Thekuwa',
    time: 'Snack',
    calories: 180,
    dietType: 'Vegetarian',
    description: 'Deep-fried snack made with chickpeas.',
  },
  {
    id: 145,
    name: 'Makai Ko Thekuwa',
    time: 'Snack',
    calories: 190,
    dietType: 'Vegetarian',
    description: 'Deep-fried snack made with corn flour.',
  },
  {
    id: 146,
    name: 'Kodo Ko Thekuwa',
    time: 'Snack',
    calories: 180,
    dietType: 'Vegetarian',
    description: 'Deep-fried snack made with finger millet.',
  },
  {
    id: 147,
    name: 'Phapar Ko Thekuwa',
    time: 'Snack',
    calories: 170,
    dietType: 'Vegetarian',
    description: 'Deep-fried snack made with buckwheat.',
  },
  {
    id: 148,
    name: 'Gundruk Ko Pakoda',
    time: 'Snack',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Fritters made with fermented greens.',
  },
  {
    id: 149,
    name: 'Masyaura Ko Pakoda',
    time: 'Snack',
    calories: 210,
    dietType: 'Vegetarian',
    description: 'Fritters made with dried lentil balls.',
  },
  {
    id: 150,
    name: 'Bodi Ko Pakoda',
    time: 'Snack',
    calories: 220,
    dietType: 'Vegetarian',
    description: 'Fritters made with black-eyed peas.',
  },
  {
    id: 151,
    name: 'Chana Ko Pakoda',
    time: 'Snack',
    calories: 230,
    dietType: 'Vegetarian',
    description: 'Fritters made with chickpeas.',
  },
  {
    id: 152,
    name: 'Makai Ko Pakoda',
    time: 'Snack',
    calories: 240,
    dietType: 'Vegetarian',
    description: 'Fritters made with corn flour.',
  },
  {
    id: 153,
    name: 'Kodo Ko Pakoda',
    time: 'Snack',
    calories: 230,
    dietType: 'Vegetarian',
    description: 'Fritters made with finger millet.',
  },
  {
    id: 154,
    name: 'Phapar Ko Pakoda',
    time: 'Snack',
    calories: 220,
    dietType: 'Vegetarian',
    description: 'Fritters made with buckwheat.',
  },
  {
    id: 155,
    name: 'Gundruk Ko Chop',
    time: 'Snack',
    calories: 180,
    dietType: 'Vegetarian',
    description: 'Cutlets made with fermented greens.',
  },
  {
    id: 156,
    name: 'Masyaura Ko Chop',
    time: 'Snack',
    calories: 190,
    dietType: 'Vegetarian',
    description: 'Cutlets made with dried lentil balls.',
  },
  {
    id: 157,
    name: 'Bodi Ko Chop',
    time: 'Snack',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Cutlets made with black-eyed peas.',
  },
  {
    id: 158,
    name: 'Chana Ko Chop',
    time: 'Snack',
    calories: 210,
    dietType: 'Vegetarian',
    description: 'Cutlets made with chickpeas.',
  },
  {
    id: 159,
    name: 'Makai Ko Chop',
    time: 'Snack',
    calories: 220,
    dietType: 'Vegetarian',
    description: 'Cutlets made with corn flour.',
  },
  {
    id: 160,
    name: 'Kodo Ko Chop',
    time: 'Snack',
    calories: 210,
    dietType: 'Vegetarian',
    description: 'Cutlets made with finger millet.',
  },
  {
    id: 161,
    name: 'Phapar Ko Chop',
    time: 'Snack',
    calories: 200,
    dietType: 'Vegetarian',
    description: 'Cutlets made with buckwheat.',
  },
  {
    id: 162,
    name: 'Gundruk Ko Momo',
    time: 'Snack',
    calories: 250,
    dietType: 'Vegetarian',
    description: 'Dumplings filled with fermented greens.',
  },
  {
    id: 163,
    name: 'Masyaura Ko Momo',
    time: 'Snack',
    calories: 260,
    dietType: 'Vegetarian',
    description: 'Dumplings filled with dried lentil balls.',
  },
  {
    id: 164,
    name: 'Bodi Ko Momo',
    time: 'Snack',
    calories: 270,
    dietType: 'Vegetarian',
    description: 'Dumplings filled with black-eyed peas.',
  },
  {
    id: 165,
    name: 'Chana Ko Momo',
    time: 'Snack',
    calories: 280,
    dietType: 'Vegetarian',
    description: 'Dumplings filled with chickpeas.',
  },
  {
    id: 166,
    name: 'Makai Ko Momo',
    time: 'Snack',
    calories: 290,
    dietType: 'Vegetarian',
    description: 'Dumplings filled with corn flour.',
  },
  {
    id: 167,
    name: 'Kodo Ko Momo',
    time: 'Snack',
    calories: 280,
    dietType: 'Vegetarian',
    description: 'Dumplings filled with finger millet.',
  },
  {
    id: 168,
    name: 'Phapar Ko Momo',
    time: 'Snack',
    calories: 270,
    dietType: 'Vegetarian',
    description: 'Dumplings filled with buckwheat.',
  },
  {
    id: 169,
    name: 'Gundruk Ko Chowmein',
    time: 'Lunch/Dinner',
    calories: 350,
    dietType: 'Vegetarian',
    description: 'Stir-fried noodles with fermented greens.',
  },
  {
    id: 170,
    name: 'Masyaura Ko Chowmein',
    time: 'Lunch/Dinner',
    calories: 360,
    dietType: 'Vegetarian',
    description: 'Stir-fried noodles with dried lentil balls.',
  },
  {
    id: 171,
    name: 'Bodi Ko Chowmein',
    time: 'Lunch/Dinner',
    calories: 370,
    dietType: 'Vegetarian',
    description: 'Stir-fried noodles with black-eyed peas.',
  },
  {
    id: 172,
    name: 'Chana Ko Chowmein',
    time: 'Lunch/Dinner',
    calories: 380,
    dietType: 'Vegetarian',
    description: 'Stir-fried noodles with chickpeas.',
  },
  {
    id: 173,
    name: 'Makai Ko Chowmein',
    time: 'Lunch/Dinner',
    calories: 390,
    dietType: 'Vegetarian',
    description: 'Stir-fried noodles with corn flour.',
  },
  {
    id: 174,
    name: 'Kodo Ko Chowmein',
    time: 'Lunch/Dinner',
    calories: 380,
    dietType: 'Vegetarian',
    description: 'Stir-fried noodles with finger millet.',
  },
  {
    id: 175,
    name: 'Phapar Ko Chowmein',
    time: 'Lunch/Dinner',
    calories: 370,
    dietType: 'Vegetarian',
    description: 'Stir-fried noodles with buckwheat.',
  },
  {
    id: 176,
    name: 'Gundruk Ko Pizza',
    time: 'Lunch/Dinner',
    calories: 400,
    dietType: 'Vegetarian',
    description: 'Pizza topped with fermented greens.',
  },
  {
    id: 177,
    name: 'Masyaura Ko Pizza',
    time: 'Lunch/Dinner',
    calories: 410,
    dietType: 'Vegetarian',
    description: 'Pizza topped with dried lentil balls.',
  },
  {
    id: 178,
    name: 'Bodi Ko Pizza',
    time: 'Lunch/Dinner',
    calories: 420,
    dietType: 'Vegetarian',
    description: 'Pizza topped with black-eyed peas.',
  },
  {
    id: 179,
    name: 'Chana Ko Pizza',
    time: 'Lunch/Dinner',
    calories: 430,
    dietType: 'Vegetarian',
    description: 'Pizza topped with chickpeas.',
  },
  {
    id: 180,
    name: 'Makai Ko Pizza',
    time: 'Lunch/Dinner',
    calories: 440,
    dietType: 'Vegetarian',
    description: 'Pizza topped with corn flour.',
  },
  {
    id: 181,
    name: 'Kodo Ko Pizza',
    time: 'Lunch/Dinner',
    calories: 430,
    dietType: 'Vegetarian',
    description: 'Pizza topped with finger millet.',
  },
  {
    id: 182,
    name: 'Phapar Ko Pizza',
    time: 'Lunch/Dinner',
    calories: 420,
    dietType: 'Vegetarian',
    description: 'Pizza topped with buckwheat.',
  },
  {
    id: 183,
    name: 'Gundruk Ko Burger',
    time: 'Lunch/Dinner',
    calories: 450,
    dietType: 'Vegetarian',
    description: 'Burger with patty made from fermented greens.',
  },
  {
    id: 184,
    name: 'Masyaura Ko Burger',
    time: 'Lunch/Dinner',
    calories: 460,
    dietType: 'Vegetarian',
    description: 'Burger with patty made from dried lentil balls.',
  },
  {
    id: 185,
    name: 'Bodi Ko Burger',
    time: 'Lunch/Dinner',
    calories: 470,
    dietType: 'Vegetarian',
    description: 'Burger with patty made from black-eyed peas.',
  },
  {
    id: 186,
    name: 'Chana Ko Burger',
    time: 'Lunch/Dinner',
    calories: 480,
    dietType: 'Vegetarian',
    description: 'Burger with patty made from chickpeas.',
  },
  {
    id: 187,
    name: 'Makai Ko Burger',
    time: 'Lunch/Dinner',
    calories: 490,
    dietType: 'Vegetarian',
    description: 'Burger with patty made from corn flour.',
  },
  {
    id: 188,
    name: 'Kodo Ko Burger',
    time: 'Lunch/Dinner',
    calories: 480,
    dietType: 'Vegetarian',
    description: 'Burger with patty made from finger millet.',
  },
  {
    id: 189,
    name: 'Phapar Ko Burger',
    time: 'Lunch/Dinner',
    calories: 470,
    dietType: 'Vegetarian',
    description: 'Burger with patty made from buckwheat.',
  },
  {
    id: 190,
    name: 'Gundruk Ko Sandwich',
    time: 'Breakfast/Lunch',
    calories: 350,
    dietType: 'Vegetarian',
    description: 'Sandwich filled with fermented greens.',
  },
  {
    id: 191,
    name: 'Masyaura Ko Sandwich',
    time: 'Breakfast/Lunch',
    calories: 360,
    dietType: 'Vegetarian',
    description: 'Sandwich filled with dried lentil balls.',
  },
  {
    id: 192,
    name: 'Bodi Ko Sandwich',
    time: 'Breakfast/Lunch',
    calories: 370,
    dietType: 'Vegetarian',
    description: 'Sandwich filled with black-eyed peas.',
  },
  {
    id: 193,
    name: 'Chana Ko Sandwich',
    time: 'Breakfast/Lunch',
    calories: 380,
    dietType: 'Vegetarian',
    description: 'Sandwich filled with chickpeas.',
  },
  {
    id: 194,
    name: 'Makai Ko Sandwich',
    time: 'Breakfast/Lunch',
    calories: 390,
    dietType: 'Vegetarian',
    description: 'Sandwich filled with corn flour.',
  },
  {
    id: 195,
    name: 'Kodo Ko Sandwich',
    time: 'Breakfast/Lunch',
    calories: 380,
    dietType: 'Vegetarian',
    description: 'Sandwich filled with finger millet.',
  },
  {
    id: 196,
    name: 'Phapar Ko Sandwich',
    time: 'Breakfast/Lunch',
    calories: 370,
    dietType: 'Vegetarian',
    description: 'Sandwich filled with buckwheat.',
  },
  {
    id: 197,
    name: 'Gundruk Ko Wrap',
    time: 'Lunch/Dinner',
    calories: 320,
    dietType: 'Vegetarian',
    description: 'Wrap filled with fermented greens.',
  },
  {
    id: 198,
    name: 'Masyaura Ko Wrap',
    time: 'Lunch/Dinner',
    calories: 330,
    dietType: 'Vegetarian',
    description: 'Wrap filled with dried lentil balls.',
  },
  {
    id: 199,
    name: 'Bodi Ko Wrap',
    time: 'Lunch/Dinner',
    calories: 340,
    dietType: 'Vegetarian',
    description: 'Wrap filled with black-eyed peas.',
  },
  {
    id: 200,
    name: 'Chana Ko Wrap',
    time: 'Lunch/Dinner',
    calories: 350,
    dietType: 'Vegetarian',
    description: 'Wrap filled with chickpeas.',
  },
  {
    id: 201,
    name: 'Wai Wai Noodles (Raw)',
    time: 'Snack',
    calories: 350,
    dietType: 'Junk',
    description:
      'Crunchy instant noodles eaten dry with seasoning, a popular school snack.',
  },
  {
    id: 202,
    name: 'Chowmein (Street Style)',
    time: 'Lunch/Dinner',
    calories: 500,
    dietType: 'Junk',
    description:
      'Stir-fried noodles with veggies, soy sauce, and excessive oil.',
  },
  {
    id: 203,
    name: 'Chicken Burger (Local)',
    time: 'Any',
    calories: 450,
    dietType: 'Junk',
    description: 'Deep-fried chicken patty in a bun with mayo and ketchup.',
  },
  {
    id: 204,
    name: 'Pizza (Nepali Style)',
    time: 'Dinner',
    calories: 600,
    dietType: 'Junk',
    description: 'Thick crust loaded with processed cheese and cheap toppings.',
  },
  {
    id: 205,
    name: 'Samosa',
    time: 'Snack',
    calories: 300,
    dietType: 'Junk',
    description: 'Deep-fried pastry stuffed with spiced potatoes.',
  },
  {
    id: 206,
    name: 'Pakoda',
    time: 'Snack',
    calories: 250,
    dietType: 'Junk',
    description: 'Deep-fried fritters made of veggies or meat.',
  },
  {
    id: 207,
    name: 'Chicken Sekuwa (Street)',
    time: 'Snack',
    calories: 400,
    dietType: 'Junk',
    description: 'Grilled chicken with excess oil and MSG.',
  },
  {
    id: 208,
    name: 'French Fries (Street)',
    time: 'Snack',
    calories: 350,
    dietType: 'Junk',
    description: 'Deep-fried potatoes with chili powder.',
  },
  {
    id: 209,
    name: 'Chana Chaat',
    time: 'Snack',
    calories: 280,
    dietType: 'Junk',
    description: 'Spicy chickpeas with processed sauces.',
  },
  {
    id: 210,
    name: 'Panipuri (Street)',
    time: 'Snack',
    calories: 200,
    dietType: 'Junk',
    description: 'Fried puris with questionable water hygiene.',
  },
  {
    id: 211,
    name: 'Lays Chips',
    time: 'Snack',
    calories: 160,
    dietType: 'Junk',
    description: 'Processed potato chips with artificial flavors.',
  },
  {
    id: 212,
    name: 'Kurkure',
    time: 'Snack',
    calories: 140,
    dietType: 'Junk',
    description: 'Corn-based crunchy snacks with excess salt.',
  },
  {
    id: 213,
    name: 'Haku Choyela',
    time: 'Snack',
    calories: 380,
    dietType: 'Junk',
    description: 'Overcooked, oily meat with excessive spices.',
  },
  {
    id: 214,
    name: 'Ice Cream (Local)',
    time: 'Dessert',
    calories: 300,
    dietType: 'Junk',
    description: 'High-sugar, artificial-flavored ice cream.',
  },
  {
    id: 215,
    name: 'Cold Drinks (Coca-Cola, Sprite)',
    time: 'Drink',
    calories: 150,
    dietType: 'Junk',
    description: 'Carbonated sugary beverages.',
  },
  {
    id: 216,
    name: 'Energy Drinks (Red Bull, Tiger)',
    time: 'Drink',
    calories: 120,
    dietType: 'Junk',
    description: 'High-caffeine, high-sugar drinks.',
  },
  {
    id: 217,
    name: 'Chocolate Bars (Local)',
    time: 'Snack',
    calories: 250,
    dietType: 'Junk',
    description: 'Cheap chocolates with palm oil and sugar.',
  },
  {
    id: 218,
    name: 'Biscuits (Mayos, Glucose)',
    time: 'Snack',
    calories: 180,
    dietType: 'Junk',
    description: 'Refined flour biscuits with sugar glaze.',
  },
  {
    id: 219,
    name: 'Instant Noodles (Cooked)',
    time: 'Lunch/Dinner',
    calories: 400,
    dietType: 'Junk',
    description: 'MSG-loaded noodles with little nutrition.',
  },
  {
    id: 220,
    name: 'Chicken Sausage',
    time: 'Snack',
    calories: 280,
    dietType: 'Junk',
    description: 'Processed meat with preservatives.',
  },
  {
    id: 221,
    name: 'Egg Roll (Street)',
    time: 'Snack',
    calories: 350,
    dietType: 'Junk',
    description: 'Oily paratha with egg and sauces.',
  },
  {
    id: 222,
    name: 'Chicken Chowmein',
    time: 'Lunch/Dinner',
    calories: 550,
    dietType: 'Junk',
    description: 'Noodles with cheap oil and minimal veggies.',
  },
  {
    id: 223,
    name: 'Momo (Frozen, Reheated)',
    time: 'Any',
    calories: 450,
    dietType: 'Junk',
    description: 'Low-quality meat or stale veggie fillings.',
  },
  {
    id: 224,
    name: 'Jhol Momo (Street)',
    time: 'Any',
    calories: 500,
    dietType: 'Junk',
    description: 'Momo in oily, MSG-heavy soup.',
  },
  {
    id: 225,
    name: 'Fried Chicken (Local)',
    time: 'Any',
    calories: 600,
    dietType: 'Junk',
    description: 'Deep-fried in reused oil with excess salt.',
  },
  {
    id: 226,
    name: 'Aloo Chop',
    time: 'Snack',
    calories: 320,
    dietType: 'Junk',
    description: 'Deep-fried potato cutlets with breading.',
  },
  {
    id: 227,
    name: 'Nepali Hot Dog',
    time: 'Snack',
    calories: 380,
    dietType: 'Junk',
    description: 'Sausage in bun with ketchup and mayo.',
  },
  {
    id: 228,
    name: 'Cheese Ball',
    time: 'Snack',
    calories: 200,
    dietType: 'Junk',
    description: 'Deep-fried cheese-filled dough balls.',
  },
  {
    id: 229,
    name: 'Doughnut (Local)',
    time: 'Snack',
    calories: 300,
    dietType: 'Junk',
    description: 'Sugar-glazed, deep-fried dough.',
  },
  {
    id: 230,
    name: 'Cup Noodles',
    time: 'Any',
    calories: 350,
    dietType: 'Junk',
    description: 'Instant noodles with preservatives.',
  },
  {
    id: 231,
    name: 'Chocolate Momo',
    time: 'Dessert',
    calories: 400,
    dietType: 'Junk',
    description: 'Deep-fried momo with chocolate filling.',
  },
  {
    id: 232,
    name: 'Puff Pastry (Local)',
    time: 'Snack',
    calories: 280,
    dietType: 'Junk',
    description: 'Butter-laden pastry with cheap fillings.',
  },
  {
    id: 233,
    name: 'Bhujia',
    time: 'Snack',
    calories: 180,
    dietType: 'Junk',
    description: 'Deep-fried noodle-like snack.',
  },
  {
    id: 234,
    name: 'Chocolate Sandwich',
    time: 'Snack',
    calories: 350,
    dietType: 'Junk',
    description: 'Bread with Nutella or cheap chocolate spread.',
  },
  {
    id: 235,
    name: 'Veg Burger (Street)',
    time: 'Snack',
    calories: 400,
    dietType: 'Junk',
    description: 'Deep-fried patty with sauces in a bun.',
  },
  {
    id: 236,
    name: 'Chicken Popcorn',
    time: 'Snack',
    calories: 320,
    dietType: 'Junk',
    description: 'Bite-sized deep-fried chicken pieces.',
  },
  {
    id: 237,
    name: 'Cheese Chowmein',
    time: 'Lunch/Dinner',
    calories: 600,
    dietType: 'Junk',
    description: 'Noodles overloaded with processed cheese.',
  },
  {
    id: 238,
    name: 'Chicken Pizza (Local)',
    time: 'Dinner',
    calories: 700,
    dietType: 'Junk',
    description: 'Thick crust with fatty meat and cheese.',
  },
  {
    id: 239,
    name: 'Chocolate Momo',
    time: 'Dessert',
    calories: 380,
    dietType: 'Junk',
    description: 'Steamed momo with molten chocolate.',
  },
  {
    id: 240,
    name: 'Chicken Lollipop',
    time: 'Snack',
    calories: 420,
    dietType: 'Junk',
    description: 'Deep-fried chicken wings with sauces.',
  },
  {
    id: 241,
    name: 'Cheese Balls (Packaged)',
    time: 'Snack',
    calories: 200,
    dietType: 'Junk',
    description: 'Cheese-flavored extruded snacks.',
  },
  {
    id: 242,
    name: 'Chocolate Biscuits',
    time: 'Snack',
    calories: 220,
    dietType: 'Junk',
    description: 'Sugar-coated biscuits with fake chocolate.',
  },
  {
    id: 243,
    name: 'Candy Bars',
    time: 'Snack',
    calories: 150,
    dietType: 'Junk',
    description: 'High-fructose corn syrup candies.',
  },
  {
    id: 244,
    name: 'Potato Twisters',
    time: 'Snack',
    calories: 180,
    dietType: 'Junk',
    description: 'Spiral-cut fried potatoes with seasoning.',
  },
  {
    id: 245,
    name: 'Chocolate Milk (Packaged)',
    time: 'Drink',
    calories: 250,
    dietType: 'Junk',
    description: 'Sugar-loaded flavored milk.',
  },
  {
    id: 246,
    name: 'Fried Ice Cream',
    time: 'Dessert',
    calories: 450,
    dietType: 'Junk',
    description: 'Deep-fried ice cream with coating.',
  },
  {
    id: 247,
    name: 'Chicken Tikka (Street)',
    time: 'Snack',
    calories: 500,
    dietType: 'Junk',
    description: 'Overcooked, oily chicken pieces.',
  },
  {
    id: 248,
    name: 'Cheese Fries',
    time: 'Snack',
    calories: 480,
    dietType: 'Junk',
    description: 'French fries drenched in cheese sauce.',
  },
  {
    id: 249,
    name: 'Chocolate Pancake',
    time: 'Breakfast',
    calories: 400,
    dietType: 'Junk',
    description: 'Sugar-loaded pancake with syrup.',
  },
  {
    id: 250,
    name: 'Chicken Nuggets (Local)',
    time: 'Snack',
    calories: 350,
    dietType: 'Junk',
    description: 'Processed chicken deep-fried in oil.',
  },
  {
    id: 251,
    name: 'Milkshake (Street)',
    time: 'Drink',
    calories: 400,
    dietType: 'Junk',
    description: 'Ice cream, sugar, and artificial flavors blended.',
  },
  {
    id: 252,
    name: 'Chocolate Waffle',
    time: 'Snack',
    calories: 450,
    dietType: 'Junk',
    description: 'Sugar-loaded waffle with toppings.',
  },
  {
    id: 253,
    name: 'Chicken Patty',
    time: 'Snack',
    calories: 380,
    dietType: 'Junk',
    description: 'Deep-fried chicken cutlet in a bun.',
  },
  {
    id: 254,
    name: 'Cheese Toast',
    time: 'Snack',
    calories: 300,
    dietType: 'Junk',
    description: 'Bread loaded with processed cheese.',
  },
  {
    id: 255,
    name: 'Chocolate Muffin',
    time: 'Snack',
    calories: 350,
    dietType: 'Junk',
    description: 'Sugar and oil-heavy cake-like muffin.',
  },
  {
    id: 256,
    name: 'Chicken Cutlet',
    time: 'Snack',
    calories: 420,
    dietType: 'Junk',
    description: 'Deep-fried breaded chicken.',
  },
  {
    id: 257,
    name: 'Cheese Momo',
    time: 'Snack',
    calories: 450,
    dietType: 'Junk',
    description: 'Momo stuffed with processed cheese.',
  },
  {
    id: 258,
    name: 'Chocolate Pastry',
    time: 'Dessert',
    calories: 380,
    dietType: 'Junk',
    description: 'Layered pastry with fake chocolate cream.',
  },
  {
    id: 259,
    name: 'Chicken Wrap (Street)',
    time: 'Snack',
    calories: 500,
    dietType: 'Junk',
    description: 'Oily paratha with chicken and sauces.',
  },
  {
    id: 260,
    name: 'Cheese Pasta (Local)',
    time: 'Lunch/Dinner',
    calories: 550,
    dietType: 'Junk',
    description: 'Overcooked pasta with cheap cheese sauce.',
  },
  {
    id: 261,
    name: 'Chocolate Cookies',
    time: 'Snack',
    calories: 200,
    dietType: 'Junk',
    description: 'Sugar and palm oil-based cookies.',
  },
  {
    id: 262,
    name: 'Chicken Cheese Roll',
    time: 'Snack',
    calories: 480,
    dietType: 'Junk',
    description: 'Deep-fried roll with chicken and cheese.',
  },
  {
    id: 263,
    name: 'Cheese Garlic Bread',
    time: 'Snack',
    calories: 350,
    dietType: 'Junk',
    description: 'Bread loaded with butter and cheese.',
  },
  {
    id: 264,
    name: 'Chocolate Brownie',
    time: 'Dessert',
    calories: 400,
    dietType: 'Junk',
    description: 'Sugar and oil-heavy baked dessert.',
  },
  {
    id: 265,
    name: 'Chicken Cheese Sandwich',
    time: 'Lunch',
    calories: 600,
    dietType: 'Junk',
    description: 'Bread with fried chicken and melted cheese.',
  },
  {
    id: 266,
    name: 'Cheese Nachos',
    time: 'Snack',
    calories: 450,
    dietType: 'Junk',
    description: 'Fried tortilla chips with cheese dip.',
  },
  {
    id: 267,
    name: 'Chocolate Ice Cream (Local)',
    time: 'Dessert',
    calories: 350,
    dietType: 'Junk',
    description: 'Artificial chocolate-flavored ice cream.',
  },
  {
    id: 268,
    name: 'Chicken Cheese Momo',
    time: 'Snack',
    calories: 500,
    dietType: 'Junk',
    description: 'Momo stuffed with chicken and cheese.',
  },
  {
    id: 269,
    name: 'Cheese Fries with Mayo',
    time: 'Snack',
    calories: 550,
    dietType: 'Junk',
    description: 'French fries with cheese and mayonnaise.',
  },
  {
    id: 270,
    name: 'Chocolate Donut',
    time: 'Snack',
    calories: 380,
    dietType: 'Junk',
    description: 'Deep-fried dough with chocolate glaze.',
  },
  {
    id: 271,
    name: 'Chicken Cheese Burger',
    time: 'Lunch/Dinner',
    calories: 700,
    dietType: 'Junk',
    description: 'Deep-fried chicken patty with extra cheese.',
  },
  {
    id: 272,
    name: 'Cheese Puff',
    time: 'Snack',
    calories: 180,
    dietType: 'Junk',
    description: 'Cheese-flavored extruded corn snack.',
  },
  {
    id: 273,
    name: 'Chocolate Cheesecake',
    time: 'Dessert',
    calories: 500,
    dietType: 'Junk',
    description: 'Sugar and cream cheese-heavy dessert.',
  },
  {
    id: 274,
    name: 'Chicken Cheese Pizza',
    time: 'Dinner',
    calories: 800,
    dietType: 'Junk',
    description: 'Thick crust with processed meat and cheese.',
  },
  {
    id: 275,
    name: 'Cheese Corn Balls',
    time: 'Snack',
    calories: 300,
    dietType: 'Junk',
    description: 'Deep-fried corn and cheese mixture.',
  },
  {
    id: 276,
    name: 'Chocolate Pancake Roll',
    time: 'Breakfast',
    calories: 450,
    dietType: 'Junk',
    description: 'Pancake rolled with chocolate spread.',
  },
  {
    id: 277,
    name: 'Chicken Cheese Puff',
    time: 'Snack',
    calories: 350,
    dietType: 'Junk',
    description: 'Deep-fried pastry with chicken and cheese.',
  },
  {
    id: 278,
    name: 'Cheese Masala Maggi',
    time: 'Lunch/Dinner',
    calories: 500,
    dietType: 'Junk',
    description: 'Instant noodles with processed cheese.',
  },
  {
    id: 279,
    name: 'Chocolate Sandwich Biscuit',
    time: 'Snack',
    calories: 220,
    dietType: 'Junk',
    description: 'Two biscuits with chocolate filling.',
  },
  {
    id: 280,
    name: 'Chicken Cheese Cutlet',
    time: 'Snack',
    calories: 480,
    dietType: 'Junk',
    description: 'Deep-fried breaded chicken and cheese.',
  },
  {
    id: 281,
    name: 'Cheese Chilli Momo',
    time: 'Snack',
    calories: 550,
    dietType: 'Junk',
    description: 'Fried momo with cheese and spicy sauce.',
  },
  {
    id: 282,
    name: 'Chocolate Chip Cookie',
    time: 'Snack',
    calories: 200,
    dietType: 'Junk',
    description: 'Butter and sugar-heavy cookie with chips.',
  },
  {
    id: 283,
    name: 'Chicken Cheese Chowmein',
    time: 'Lunch/Dinner',
    calories: 650,
    dietType: 'Junk',
    description: 'Noodles with fried chicken and cheese.',
  },
  {
    id: 284,
    name: 'Cheese Garlic Naan',
    time: 'Dinner',
    calories: 400,
    dietType: 'Junk',
    description: 'Butter and cheese-loaded naan bread.',
  },
  {
    id: 285,
    name: 'Chocolate Cheese Cake',
    time: 'Dessert',
    calories: 550,
    dietType: 'Junk',
    description: 'Layered cake with cream cheese and chocolate.',
  },
  {
    id: 286,
    name: 'Chicken Cheese Tikka',
    time: 'Snack',
    calories: 500,
    dietType: 'Junk',
    description: 'Grilled chicken with melted cheese.',
  },
  {
    id: 287,
    name: 'Cheese Corn Momo',
    time: 'Snack',
    calories: 450,
    dietType: 'Junk',
    description: 'Steamed momo with sweet corn and cheese.',
  },
  {
    id: 288,
    name: 'Chocolate Cheese Toast',
    time: 'Breakfast',
    calories: 400,
    dietType: 'Junk',
    description: 'Bread with chocolate and cheese mix.',
  },
  {
    id: 289,
    name: 'Chicken Cheese Samosa',
    time: 'Snack',
    calories: 380,
    dietType: 'Junk',
    description: 'Deep-fried pastry with chicken and cheese.',
  },
  {
    id: 290,
    name: 'Cheese Chilli Potato',
    time: 'Snack',
    calories: 500,
    dietType: 'Junk',
    description: 'Fried potatoes with cheese and spices.',
  },
  {
    id: 291,
    name: 'Chocolate Cheese Roll',
    time: 'Dessert',
    calories: 420,
    dietType: 'Junk',
    description: 'Sweet roll with chocolate and cheese.',
  },
  {
    id: 292,
    name: 'Chicken Cheese Pakoda',
    time: 'Snack',
    calories: 450,
    dietType: 'Junk',
    description: 'Deep-fried chicken and cheese fritters.',
  },
  {
    id: 293,
    name: 'Cheese Chilli Chowmein',
    time: 'Lunch/Dinner',
    calories: 600,
    dietType: 'Junk',
    description: 'Spicy noodles with melted cheese.',
  },
  {
    id: 294,
    name: 'Chocolate Cheese Momo',
    time: 'Dessert',
    calories: 480,
    dietType: 'Junk',
    description: 'Steamed momo with chocolate and cheese.',
  },
  {
    id: 295,
    name: 'Chicken Cheese Spring Roll',
    time: 'Snack',
    calories: 400,
    dietType: 'Junk',
    description: 'Crispy roll with chicken and cheese.',
  },
  {
    id: 296,
    name: 'Cheese Masala Papad',
    time: 'Snack',
    calories: 250,
    dietType: 'Junk',
    description: 'Fried papad topped with cheese.',
  },
  {
    id: 297,
    name: 'Chocolate Cheese Pancake',
    time: 'Breakfast',
    calories: 500,
    dietType: 'Junk',
    description: 'Pancake with chocolate and cheese filling.',
  },
  {
    id: 298,
    name: 'Chicken Cheese Kebab',
    time: 'Snack',
    calories: 450,
    dietType: 'Junk',
    description: 'Grilled chicken and cheese skewers.',
  },
  {
    id: 299,
    name: 'Cheese Chilli Chicken',
    time: 'Dinner',
    calories: 650,
    dietType: 'Junk',
    description: 'Spicy chicken with melted cheese.',
  },
  {
    id: 300,
    name: 'Chocolate Cheese Samosa',
    time: 'Dessert',
    calories: 380,
    dietType: 'Junk',
    description: 'Sweet samosa with chocolate and cheese.',
  },
];
